from gi.repository import Gtk

class DetailsView(Gtk.Box):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_orientation(Gtk.Orientation.VERTICAL)
        self.set_spacing(15)
        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="App ID", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)

        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="Name", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)

        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="Sort As", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)

        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="Developer", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)

        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="Publisher", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)

        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="Steam Release Date", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)

        app_id_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, hexpand=True, spacing=5)
        app_id_label = Gtk.Label(label="Original Release Date", vexpand=False, halign=Gtk.Align.START)
        app_id_label.set_css_classes(['entry_title'])
        app_id_entry = Gtk.Entry(vexpand=False, hexpand=True)
        app_id_box.append(app_id_label)
        app_id_box.append(app_id_entry)
        self.append(app_id_box)
